server:
  port: 8080

spring:
  application:
    name: HeiMaComments
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima_comments?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: jqc004118

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: edu.qingchenjia.heimacomments.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
